name: stock-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - fastapi
  - uvicorn
  - joblib
  - pytorch
  - pip:
      - yfinance
      - mlflow
